import { useWeb3React } from '@web3-react/core'
import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { connector } from '../config/web3'


export default function Home() {
  const {
    activate,
    active,
    deactivate,
    error,
    account,
    chainId

  } = useWeb3React()

  const connect = useCallback(() => {
    activate(connector)
    localStorage.setItem('previuslyConected', true)

  },[activate])

  useEffect(() => {
    if (localStorage.getItem('previuslyConected') === 'true')
    connect()
    
  },[connect])

  

  const disconnect = () => {
    deactivate()
    localStorage.removeItem('previuslyConected')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>iaeloko App Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://merkadapp.com">Merkadapp!</a>
        </h1>
        <br>
        </br>



        <button onClick={connect}> Conect Wallet </button>
        

        
       


      </main>
    </div>  
  )
}
