import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  useEffect(() => {
    
  })

  const connect = () => {

  }

  const disconnect = () => {

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>iaeloko App Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://merkadapp.com">Merkadapp!</a>
        </h1>
        <br></br>

        <button onClick={connect}> Conect Wallet </button>

       
      </main>
    </div>  
  )
}
